version: 2.1

jobs:
  build:
    docker:
      - image: cimg/deploy:2023.02
    steps:
      - checkout
      - setup_remote_docker:
        version: 20.10.14
      - run: make build-push

workflows:
  build_and_test:
    jobs:
      - build
